/**
 * This file generated by Apso.
 */
export enum SurveyStatusEnum {
  active = 'active',
  inactive = 'inactive',
  draft = 'draft',
}
export enum QuestionResponseTypeEnum {
  multiple_choice = 'multiple_choice',
  text = 'text',
  rating = 'rating',
}
