import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */
import * as enums from '../../enums';

export class SurveyCreate {
  @ApiProperty()
  title: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  created_by: string;
  @ApiProperty()
  status: enums.SurveyStatusEnum;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}

export class Survey {
  @ApiProperty()
  id: number;
  @ApiProperty()
  title: string;
  @ApiProperty()
  description: string;
  @ApiProperty()
  created_by: string;
  @ApiProperty()
  status: enums.SurveyStatusEnum;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
  @ApiProperty()
  created_at: Date;
  @ApiProperty()
  updated_at: Date;
}
